name: Format
description: Format sources
runs:
  using: composite
  steps:
    - run: pnpm format
      shell: bash
    - uses: ./configure-git
    - name: Commit a diff
      run: |
        if git commit -am "format [skip ci]"
        then
          git push origin HEAD:${{ github.ref }}
        fi
      shell: bash
