name: Format
description: Format sources
runs:
  using: composite
  steps:
    - run: pnpm format
      shell: bash
    - uses: tuqulore/.github/configure-git@8caf5d569132d10bb856f4c14b2530c0e9e8f1ba # main
    - name: Commit a diff
      run: |
        if git commit -am "format [skip ci]"
        then
          git push origin HEAD:${{ github.ref }}
        fi
      shell: bash
