name: Format
description: Format sources
runs:
  using: composite
  steps:
    - run: pnpm format
      shell: bash
    - name: Setup Git Config
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
      shell: bash
    - name: Commit a diff
      run: |
        if git commit -am "format [skip ci]"
        then
          git push origin HEAD:${{ github.ref }}
        fi
      shell: bash
