name: Setup
description: Setup Node and Package Manager
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: pnpm
    - run: pnpm install
      shell: bash
